using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Godot;

public class ColorDict
{
    public static Dictionary<string, Godot.Color> NamedColors = new Dictionary<string, Godot.Color>
    {
        { "ALICEBLUE", Colors.AliceBlue },
        { "ANTIQUEWHITE", Colors.AntiqueWhite },
        { "AQUA", Colors.Aqua },
        { "AQUAMARINE", Colors.Aquamarine },
        { "AZURE", Colors.Azure },
        { "BEIGE", Colors.Beige },
        { "BISQUE", Colors.Bisque },
        { "BLACK", Colors.Black },
        { "BLANCHEDALMOND", Colors.BlanchedAlmond },
        { "BLUE", Colors.Blue },
        { "BLUEVIOLET", Colors.BlueViolet },
        { "BROWN", Colors.Brown },
        { "BURLYWOOD", Colors.Burlywood },
        { "CADETBLUE", Colors.CadetBlue },
        { "CHARTREUSE", Colors.Chartreuse },
        { "CHOCOLATE", Colors.Chocolate },
        { "CORAL", Colors.Coral },
        { "CORNFLOWERBLUE", Colors.CornflowerBlue },
        { "CORNSILK", Colors.Cornsilk },
        { "CRIMSON", Colors.Crimson },
        { "CYAN", Colors.Cyan },
        { "DARKBLUE", Colors.DarkBlue },
        { "DARKCYAN", Colors.DarkCyan },
        { "DARKGOLDENROD", Colors.DarkGoldenrod },
        { "DARKGRAY", Colors.DarkGray },
        { "DARKGREEN", Colors.DarkGreen },
        { "DARKKHAKI", Colors.DarkKhaki },
        { "DARKMAGENTA", Colors.DarkMagenta },
        { "DARKOLIVEGREEN", Colors.DarkOliveGreen },
        { "DARKORANGE", Colors.DarkOrange },
        { "DARKORCHID", Colors.DarkOrchid },
        { "DARKRED", Colors.DarkRed },
        { "DARKSALMON", Colors.DarkSalmon },
        { "DARKSEAGREEN", Colors.DarkSeaGreen },
        { "DARKSLATEBLUE", Colors.DarkSlateBlue },
        { "DARKSLATEGRAY", Colors.DarkSlateGray },
        { "DARKTURQUOISE", Colors.DarkTurquoise },
        { "DARKVIOLET", Colors.DarkViolet },
        { "DEEPPINK", Colors.DeepPink },
        { "DEEPSKYBLUE", Colors.DeepSkyBlue },
        { "DIMGRAY", Colors.DimGray },
        { "DODGERBLUE", Colors.DodgerBlue },
        { "FIREBRICK", Colors.Firebrick },
        { "FLORALWHITE", Colors.FloralWhite },
        { "FORESTGREEN", Colors.ForestGreen },
        { "FUCHSIA", Colors.Fuchsia },
        { "GAINSBORO", Colors.Gainsboro },
        { "GHOSTWHITE", Colors.GhostWhite },
        { "GOLD", Colors.Gold },
        { "GOLDENROD", Colors.Goldenrod },
        { "GRAY", Colors.Gray },
        { "GREEN", Colors.Green },
        { "GREENYELLOW", Colors.GreenYellow },
        { "HONEYDEW", Colors.Honeydew },
        { "HOTPINK", Colors.HotPink },
        { "INDIANRED", Colors.IndianRed },
        { "INDIGO", Colors.Indigo },
        { "IVORY", Colors.Ivory },
        { "KHAKI", Colors.Khaki },
        { "LAVENDER", Colors.Lavender },
        { "LAVENDERBLUSH", Colors.LavenderBlush },
        { "LAWNGREEN", Colors.LawnGreen },
        { "LEMONCHIFFON", Colors.LemonChiffon },
        { "LIGHTBLUE", Colors.LightBlue },
        { "LIGHTCORAL", Colors.LightCoral },
        { "LIGHTCYAN", Colors.LightCyan },
        { "LIGHTGOLDENROD", Colors.LightGoldenrod },
        { "LIGHTGRAY", Colors.LightGray },
        { "LIGHTGREEN", Colors.LightGreen },
        { "LIGHTPINK", Colors.LightPink },
        { "LIGHTSALMON", Colors.LightSalmon },
        { "LIGHTSEAGREEN", Colors.LightSeaGreen },
        { "LIGHTSKYBLUE", Colors.LightSkyBlue },
        { "LIGHTSLATEGRAY", Colors.LightSlateGray },
        { "LIGHTSTEELBLUE", Colors.LightSteelBlue },
        { "LIGHTYELLOW", Colors.LightYellow },
        { "LIME", Colors.Lime },
        { "LIMEGREEN", Colors.LimeGreen },
        { "LINEN", Colors.Linen },
        { "MAGENTA", Colors.Magenta },
        { "MAROON", Colors.Maroon },
        { "MEDIUMAQUAMARINE", Colors.MediumAquamarine },
        { "MEDIUMBLUE", Colors.MediumBlue },
        { "MEDIUMORCHID", Colors.MediumOrchid },
        { "MEDIUMPURPLE", Colors.MediumPurple },
        { "MEDIUMSEAGREEN", Colors.MediumSeaGreen },
        { "MEDIUMSLATEBLUE", Colors.MediumSlateBlue },
        { "MEDIUMSPRINGGREEN", Colors.MediumSpringGreen },
        { "MEDIUMTURQUOISE", Colors.MediumTurquoise },
        { "MEDIUMVIOLETRED", Colors.MediumVioletRed },
        { "MIDNIGHTBLUE", Colors.MidnightBlue },
        { "MINTCREAM", Colors.MintCream },
        { "MISTYROSE", Colors.MistyRose },
        { "MOCCASIN", Colors.Moccasin },
        { "NAVAJOWHITE", Colors.NavajoWhite },
        { "NAVYBLUE", Colors.NavyBlue },
        { "OLDLACE", Colors.OldLace },
        { "OLIVE", Colors.Olive },
        { "OLIVEDRAB", Colors.OliveDrab },
        { "ORANGE", Colors.Orange },
        { "ORANGERED", Colors.OrangeRed },
        { "ORCHID", Colors.Orchid },
        { "PALEGOLDENROD", Colors.PaleGoldenrod },
        { "PALEGREEN", Colors.PaleGreen },
        { "PALETURQUOISE", Colors.PaleTurquoise },
        { "PALEVIOLETRED", Colors.PaleVioletRed },
        { "PAPAYAWHIP", Colors.PapayaWhip },
        { "PEACHPUFF", Colors.PeachPuff },
        { "PERU", Colors.Peru },
        { "PINK", Colors.Pink },
        { "PLUM", Colors.Plum },
        { "POWDERBLUE", Colors.PowderBlue },
        { "PURPLE", Colors.Purple },
        { "REBECCAPURPLE", Colors.RebeccaPurple },
        { "RED", Colors.Red },
        { "ROSYBROWN", Colors.RosyBrown },
        { "ROYALBLUE", Colors.RoyalBlue },
        { "SADDLEBROWN", Colors.SaddleBrown },
        { "SALMON", Colors.Salmon },
        { "SANDYBROWN", Colors.SandyBrown },
        { "SEAGREEN", Colors.SeaGreen },
        { "SEASHELL", Colors.Seashell },
        { "SIENNA", Colors.Sienna },
        { "SILVER", Colors.Silver },
        { "SKYBLUE", Colors.SkyBlue },
        { "SLATEBLUE", Colors.SlateBlue },
        { "SLATEGRAY", Colors.SlateGray },
        { "SNOW", Colors.Snow },
        { "SPRINGGREEN", Colors.SpringGreen },
        { "STEELBLUE", Colors.SteelBlue },
        { "TAN", Colors.Tan },
        { "TEAL", Colors.Teal },
        { "THISTLE", Colors.Thistle },
        { "TOMATO", Colors.Tomato },
        { "TRANSPARENT", Colors.Transparent },
        { "TURQUOISE", Colors.Turquoise },
        { "VIOLET", Colors.Violet },
        { "WEBGRAY", Colors.WebGray },
        { "WEBGREEN", Colors.WebGreen },
        { "WEBMAROON", Colors.WebMaroon },
        { "WEBPURPLE", Colors.WebPurple },
        { "WHEAT", Colors.Wheat },
        { "WHITE", Colors.White },
        { "WHITESMOKE", Colors.WhiteSmoke },
        { "YELLOW", Colors.Yellow },
        { "YELLOWGREEN", Colors.YellowGreen }
    };
    
    public static Color GetRandomColor()
    {
        return NamedColors.ElementAt(Random.Shared.Next(0, ColorDict.NamedColors.Count)).Value;
    }
}
